service: elasticache-lambda

frameworkVersion: '>=1.21.0 <2.0.0'

provider:
  name: aws
  stage: production
  region: eu-west-1
  runtime: nodejs8.10
  environment:
    NODE_ENV: '${self:provider.stage}'
    USE_CACHE: true
    REDIS_HOST: "Fn::GetAtt": [ServerlessElasticacheReplicationGroup, ConfigurationEndPoint.Address]
    REDIS_PORT: "Fn::GetAtt": [ServerlessElasticacheReplicationGroup, ConfigurationEndPoint.Port]

functions:
  cacheTime:
    handler: index.cacheTime
    name: '${self:provider.stage}-lambda'
    description: Redis lambda
    memorySize: 128
    timeout: 6
    vpc:
      securityGroupIds:
        - "Fn::GetAtt": ServerlessSecurityGroup.GroupId
      subnetIds:
        - Ref: ServerlessPrivateSubnetA

custom:
  config:
    CACHE_INSTANCE_SIZE: cache.t2.micro

resources:
  Resources:
    ServerlessVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: "10.0.0.0/16"

    ElasticIpLambda:
      Type: AWS::EC2::EIP
      Properties:
        Domain: vpc

    InternetGatewayLambda:
      Type: AWS::EC2::InternetGateway

    VPCGatewayAttachmentLambda:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        VpcId:
          Ref: ServerlessVPC
        InternetGatewayId:
          Ref: InternetGatewayLambda

    NatGatewayLambda:
      Type: AWS::EC2::NatGateway
      Properties:
        AllocationId:
          Fn::GetAtt:
            - ElasticIpLambda
            - AllocationId
        SubnetId:
          Ref: ServerlessPublicSubnetA

    ServerlessPrivateSubnetA:
      DependsOn: ServerlessVPC
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Ref: ServerlessVPC
        AvailabilityZone: ${self:provider.region}a
        CidrBlock: "10.0.1.0/24"

    ServerlessPublicSubnetA:
      DependsOn: ServerlessVPC
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Ref: ServerlessVPC
        AvailabilityZone: ${self:provider.region}a
        CidrBlock: "10.0.2.0/24"

    DefaultPrivateRouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId:
          Ref: ServerlessVPC

    DefaultPrivateRoute:
      Type: AWS::EC2::Route
      Properties:
        RouteTableId:
          Ref: DefaultPrivateRouteTable
        DestinationCidrBlock: 0.0.0.0/0
        NatGatewayId:
          Ref: NatGatewayLambda

    DefaultPublicRouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId:
          Ref: ServerlessVPC

    DefaultPublicRoute:
      Type: AWS::EC2::Route
      Properties:
        RouteTableId:
          Ref: DefaultPublicRouteTable
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId:
          Ref: InternetGatewayLambda

    SubnetRouteTableAssociationLambdaPrivateA:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId:
          Ref: ServerlessPrivateSubnetA
        RouteTableId:
          Ref: DefaultPrivateRouteTable

    SubnetRouteTableAssociationLambdaPublicA:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId:
          Ref: ServerlessPublicSubnetA
        RouteTableId:
          Ref: DefaultPublicRouteTable

    ServerlessSecurityGroup:
      DependsOn: ServerlessVPC
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: SecurityGroup for Serverless Functions
        VpcId:
          Ref: ServerlessVPC

    ServerlessStorageSecurityGroup:
      DependsOn: ServerlessVPC
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Ingress for Redis Cluster
        VpcId:
          Ref: ServerlessVPC
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '6379'
          ToPort: '6379'
          SourceSecurityGroupId:
            Ref: ServerlessSecurityGroup

    ServerlessCacheSubnetGroup:
      Type: AWS::ElastiCache::SubnetGroup
      Properties:
        Description: "Cache Subnet Group"
        SubnetIds:
        - Ref: ServerlessPrivateSubnetA

    ServerlessElasticacheParameterGroup:
      Type: 'AWS::ElastiCache::ParameterGroup'
      Properties:
        CacheParameterGroupFamily: redis4.0
        Description: Modifications to support better performance
        Properties:
          cluster-enabled: 'yes'
          tcp-keepalive: 60
          timeout: 300
          maxmemory-policy: allkeys-lru

    ServerlessElasticacheReplicationGroup:
      Type: 'AWS::ElastiCache::ReplicationGroup'
      Version: '2015-02-02'
      Properties:
        AutomaticFailoverEnabled: true
        AutoMinorVersionUpgrade: true
        ReplicationGroupId: '${self:provider.stage}'
        ReplicationGroupDescription: 'Redis cluster - ${self:provider.stage}'
        CacheNodeType: ${self:custom.config.CACHE_INSTANCE_SIZE}
        CacheParameterGroupName:
          Ref: ServerlessElasticacheParameterGroup
        CacheSubnetGroupName:
          Ref: ServerlessCacheSubnetGroup
        Engine: redis
        EngineVersion: '4.0'
        NumNodeGroups: 1
        NodeGroupConfiguration:
          - PrimaryAvailabilityZone: '${self:provider.region}a'
            ReplicaAvailabilityZones:
              - '${self:provider.region}a'
              # - '${self:provider.region}b'
              # - '${self:provider.region}c'
            ReplicaCount: 1
        SecurityGroupIds:
          - Ref: ServerlessStorageSecurityGroup
